name: Build Bidon SDK

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: 'SDK version (e.g. 1.1.0)'
        required: true
        type: string
      adapters_version:
        description: 'Adapters version (e.g. 1.1.0.0)'
        required: true
        type: string
      upload:
        description: 'Upload to AWS?'
        required: true
        type: boolean
        default: false
      push_specs:
        description: 'Push generated podspecs to repo?'
        required: true
        type: boolean
        default: false

jobs:
  build-bidon-sdk:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.0
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build SDK via Fastlane
        run: |
          bundle exec fastlane sdk \
            version:${{ inputs.sdk_version }} \
            adapters_version:${{ inputs.adapters_version }} \
            upload:${{ inputs.upload }}
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}

      - name: Setup SSH for podspec repo
        if: ${{ inputs.push_specs }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.POD_REPO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Register CocoaPods repo
        if: ${{ inputs.push_specs }}
        run: |
          pod repo remove bidon || true
          pod repo add bidon git@github.com:bidon-io/CocoaPods-Specs.git

      - name: Push main Bidon podspec first
        if: ${{ inputs.push_specs }}
        run: |
          echo "Pushing Bidon.podspec.json first..."
          pod repo push bidon build/Podspecs/Bidon.podspec.json --allow-warnings --skip-tests --skip-import-validation

      - name: Push adapter podspecs
        if: ${{ inputs.push_specs }}
        run: |
          for spec in build/Podspecs/*.podspec.json; do
            if [[ "$spec" != *"Bidon.podspec.json" ]]; then
              echo "Pushing $spec..."
              pod repo push bidon "$spec" --allow-warnings --skip-tests --skip-import-validation
            fi
          done

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "✅ *[Bidon] SDK Build Succeeded!*\n• Version: `${{ inputs.sdk_version }}`\n• Adapters: `${{ inputs.adapters_version }}`\n• Upload: `${{ inputs.upload }}`\n• Specs pushed: `${{ inputs.push_specs }}`\n• Workflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "❌ *[Bidon] SDK Build Failed!*\n• Version: `${{ inputs.sdk_version }}`\n• Adapters: `${{ inputs.adapters_version }}`\n• Upload: `${{ inputs.upload }}`\n• Specs pushed: `${{ inputs.push_specs }}`\n• Workflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
