name: Tests Core

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests_swift:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Cache DerivedData (Swift)
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: tests-swift-deriveddata-${{ github.sha }}
          restore-keys: |
            tests-swift-deriveddata-

      - name: Configure GitHub token for CocoaPods
        run: |
          echo "machine github.com login ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Run Tests-Swift
        run: |
          set -eo pipefail
          xcodebuild test \
            -workspace BidOn.xcworkspace \
            -scheme Tests-Swift \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            -resultBundlePath Result/Tests-Swift.xcresult \
            | xcbeautify

  tests_objc:
    needs: tests_swift
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Cache DerivedData (Objective-C)
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: tests-objc-deriveddata-${{ github.sha }}
          restore-keys: |
            tests-objc-deriveddata-

      - name: Configure GitHub token for CocoaPods
        run: |
          echo "machine github.com login ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Run Tests-ObjectiveC
        run: |
          set -eo pipefail
          xcodebuild test \
            -workspace BidOn.xcworkspace \
            -scheme Tests-ObjectiveC \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            -resultBundlePath Result/Tests-ObjectiveC.xcresult \
            | xcbeautify
